// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

namespace Repositories.Migrations
{
    [DbContext(typeof(ChauffeurContext))]
    [Migration("20201105230945_AllphiFleet.1")]
    partial class AllphiFleet1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DTO.Chauffeur", b =>
                {
                    b.Property<long>("ChauffeurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Actief")
                        .HasColumnType("bit");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeboorteDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RijksRegisterNummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeRijbewijs")
                        .HasColumnType("int");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChauffeurId");

                    b.ToTable("Chauffeurs");

                    b.HasData(
                        new
                        {
                            ChauffeurId = 1L,
                            Actief = true,
                            Adres = "Bremptstraat 54",
                            GeboorteDatum = new DateTime(1979, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naam = "Bob",
                            RijksRegisterNummer = "999-888-7777",
                            TypeRijbewijs = 2,
                            Voornaam = "Uncle"
                        },
                        new
                        {
                            ChauffeurId = 2L,
                            Actief = true,
                            Adres = "Bremptstraat 54",
                            GeboorteDatum = new DateTime(1989, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Naam = "Breem",
                            RijksRegisterNummer = "999-888-1111",
                            TypeRijbewijs = 1,
                            Voornaam = "Rik"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
